# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8621a41d9da8a4866ff780fb99b0d2c0367c7a27eae3ff221056d111a7c4524848b823dec709d9d2ef2d49e5ffcc1812fbd42f81080e32ede58552678ef09165

test:
  secret_key_base: dd05825aef3417d237121b22b9d5bd5985fa361f50475d24e3c31071081dfab7c619ff5919a11fa56b3496c17e62a158ce62e3d65ca2b24ae91ccfcb30f57005

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
